openapi: 3.1.0
info:
  title: Karelia API Programming - OpenAI 3.0
  description: |-
    This is a simple OpenAI OAD.
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
    
  termsOfService: http://swagger.io/terms/
  contact:  
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: https://m.karelia.fi
servers:
  - url: http://localhost:3000
tags:           
  - name: Sample dataset
    description: Everything about your APIs
    externalDocs:
      description: Find out more
      url:  https://m.karelia.fi
 
  
paths:
    /data: 
      get: 
        tags: 
          - Sample dataset
        summary: Returns a dataset
        description: Returns a dataset with something more ...
        responses: 
          '200': 
            description: successful operation
            content: 
              application/json: 
                schema: 
                  type: array
                  items: 
                    $ref: '#/compenents/schemas/Data'
          '415':
            description: Unsupported media type
        
components:
  schemas: 
    Data: 
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 111
        forename: 
          type: string
          example: Roy
        surname: 
          type: string
          example: Fielding
    
 